name : saknoo-api-cd

on:
  push:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: publish
      run: dotnet publish ./Saknoo.API/Saknoo.API.csproj -c Release -o ./publish

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
       name: api-Artifact
       path: publish

  deploy-dev:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.3.0
          with:
           name: api-Artifact

        - name: Azure WebApp
          uses: Azure/webapps-deploy@v3.0.0
          with:
           app-name: 'saknoo-api-dev'
           publish-profile: ${{secrets.PUNLISH_PROFILE_DEV}}

